[theme]
base = "dark"
primaryColor = "#38BDF8"
backgroundColor = "#0B0F17"
secondaryBackgroundColor = "#131D2E"
textColor = "#F8FAFC"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
